//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 07:08:19 PM CET 
//


package sk.tuke.fei.kpi.nosal.milan.bte.metaconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BTEConfiguration-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BTEConfiguration-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configurationAnnotations" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="document" type="{http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration}document-type"/>
 *         &lt;element name="inputDocuments" type="{http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration}inputDocuments-type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="jaxbPackage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outputDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outputDocument" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priority" type="{http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration}priority-type"/>
 *         &lt;element name="schemaLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="warningPrinting" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="annotationType" type="{http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration}annotationType-type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BTEConfiguration-type", propOrder = {
    "configurationAnnotations",
    "document",
    "inputDocuments",
    "jaxbPackage",
    "outputDirectory",
    "outputDocument",
    "priority",
    "schemaLocation",
    "warningPrinting",
    "annotationType"
})
public class BTEConfigurationType {

    protected List<String> configurationAnnotations;
    @XmlElement(required = true)
    protected DocumentType document;
    protected List<InputDocumentsType> inputDocuments;
    @XmlElement(required = true, defaultValue = "")
    protected String jaxbPackage;
    @XmlElement(required = true, defaultValue = "")
    protected String outputDirectory;
    @XmlElement(required = true, defaultValue = "document.xml")
    protected String outputDocument;
    @XmlElement(required = true, defaultValue = "XML")
    protected PriorityType priority;
    @XmlElement(required = true, defaultValue = "document.xsd")
    protected String schemaLocation;
    @XmlElement(defaultValue = "false")
    protected boolean warningPrinting;
    protected List<AnnotationTypeType> annotationType;
    @XmlAttribute
    protected String key;

    /**
     * Gets the value of the configurationAnnotations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configurationAnnotations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigurationAnnotations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConfigurationAnnotations() {
        if (configurationAnnotations == null) {
            configurationAnnotations = new ArrayList<String>();
        }
        return this.configurationAnnotations;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType }
     *     
     */
    public DocumentType getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType }
     *     
     */
    public void setDocument(DocumentType value) {
        this.document = value;
    }

    /**
     * Gets the value of the inputDocuments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputDocuments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputDocuments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InputDocumentsType }
     * 
     * 
     */
    public List<InputDocumentsType> getInputDocuments() {
        if (inputDocuments == null) {
            inputDocuments = new ArrayList<InputDocumentsType>();
        }
        return this.inputDocuments;
    }

    /**
     * Gets the value of the jaxbPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJaxbPackage() {
        return jaxbPackage;
    }

    /**
     * Sets the value of the jaxbPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJaxbPackage(String value) {
        this.jaxbPackage = value;
    }

    /**
     * Gets the value of the outputDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputDirectory() {
        return outputDirectory;
    }

    /**
     * Sets the value of the outputDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputDirectory(String value) {
        this.outputDirectory = value;
    }

    /**
     * Gets the value of the outputDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputDocument() {
        return outputDocument;
    }

    /**
     * Sets the value of the outputDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputDocument(String value) {
        this.outputDocument = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link PriorityType }
     *     
     */
    public PriorityType getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorityType }
     *     
     */
    public void setPriority(PriorityType value) {
        this.priority = value;
    }

    /**
     * Gets the value of the schemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaLocation() {
        return schemaLocation;
    }

    /**
     * Sets the value of the schemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaLocation(String value) {
        this.schemaLocation = value;
    }

    /**
     * Gets the value of the warningPrinting property.
     * 
     */
    public boolean isWarningPrinting() {
        return warningPrinting;
    }

    /**
     * Sets the value of the warningPrinting property.
     * 
     */
    public void setWarningPrinting(boolean value) {
        this.warningPrinting = value;
    }

    /**
     * Gets the value of the annotationType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationTypeType }
     * 
     * 
     */
    public List<AnnotationTypeType> getAnnotationType() {
        if (annotationType == null) {
            annotationType = new ArrayList<AnnotationTypeType>();
        }
        return this.annotationType;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
