//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 07:08:19 PM CET 
//


package sk.tuke.fei.kpi.nosal.milan.bte.metaconfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for document-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="document-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XMLNameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="elementKinds" type="{http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration}elementKinds-type"/>
 *         &lt;element name="rootName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "document-type", propOrder = {
    "xmlNameSpace",
    "elementKinds",
    "rootName"
})
public class DocumentType {

    @XmlElement(name = "XMLNameSpace", required = true)
    protected String xmlNameSpace;
    @XmlElement(required = true)
    protected ElementKindsType elementKinds;
    @XmlElement(required = true)
    protected String rootName;

    /**
     * Gets the value of the xmlNameSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXMLNameSpace() {
        return xmlNameSpace;
    }

    /**
     * Sets the value of the xmlNameSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMLNameSpace(String value) {
        this.xmlNameSpace = value;
    }

    /**
     * Gets the value of the elementKinds property.
     * 
     * @return
     *     possible object is
     *     {@link ElementKindsType }
     *     
     */
    public ElementKindsType getElementKinds() {
        return elementKinds;
    }

    /**
     * Sets the value of the elementKinds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementKindsType }
     *     
     */
    public void setElementKinds(ElementKindsType value) {
        this.elementKinds = value;
    }

    /**
     * Gets the value of the rootName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootName() {
        return rootName;
    }

    /**
     * Sets the value of the rootName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootName(String value) {
        this.rootName = value;
    }

}
