//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 07:08:19 PM CET 
//


package sk.tuke.fei.kpi.nosal.milan.bte.metaconfiguration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sk.tuke.fei.kpi.nosal.milan.bte.metaconfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Metaconfiguration_QNAME = new QName("http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration", "metaconfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.tuke.fei.kpi.nosal.milan.bte.metaconfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeclMethodType }
     * 
     */
    public DeclMethodType createDeclMethodType() {
        return new DeclMethodType();
    }

    /**
     * Create an instance of {@link InsideType }
     * 
     */
    public InsideType createInsideType() {
        return new InsideType();
    }

    /**
     * Create an instance of {@link TargetElementType }
     * 
     */
    public TargetElementType createTargetElementType() {
        return new TargetElementType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link InputDocumentsType }
     * 
     */
    public InputDocumentsType createInputDocumentsType() {
        return new InputDocumentsType();
    }

    /**
     * Create an instance of {@link SkipType }
     * 
     */
    public SkipType createSkipType() {
        return new SkipType();
    }

    /**
     * Create an instance of {@link ElementKindsType }
     * 
     */
    public ElementKindsType createElementKindsType() {
        return new ElementKindsType();
    }

    /**
     * Create an instance of {@link StaticModifierType }
     * 
     */
    public StaticModifierType createStaticModifierType() {
        return new StaticModifierType();
    }

    /**
     * Create an instance of {@link MapsToType }
     * 
     */
    public MapsToType createMapsToType() {
        return new MapsToType();
    }

    /**
     * Create an instance of {@link AnnotationTypeType }
     * 
     */
    public AnnotationTypeType createAnnotationTypeType() {
        return new AnnotationTypeType();
    }

    /**
     * Create an instance of {@link CopyBranchType }
     * 
     */
    public CopyBranchType createCopyBranchType() {
        return new CopyBranchType();
    }

    /**
     * Create an instance of {@link WrapperType }
     * 
     */
    public WrapperType createWrapperType() {
        return new WrapperType();
    }

    /**
     * Create an instance of {@link BTEConfigurationType }
     * 
     */
    public BTEConfigurationType createBTEConfigurationType() {
        return new BTEConfigurationType();
    }

    /**
     * Create an instance of {@link MetaconfigurationType }
     * 
     */
    public MetaconfigurationType createMetaconfigurationType() {
        return new MetaconfigurationType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaconfigurationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration", name = "metaconfiguration")
    public JAXBElement<MetaconfigurationType> createMetaconfiguration(MetaconfigurationType value) {
        return new JAXBElement<MetaconfigurationType>(_Metaconfiguration_QNAME, MetaconfigurationType.class, null, value);
    }

}
