//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 07:08:19 PM CET 
//


package sk.tuke.fei.kpi.nosal.milan.bte.metaconfiguration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for targetCoupling-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="targetCoupling-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PACKAGE"/>
 *     &lt;enumeration value="TOP_PACKAGE"/>
 *     &lt;enumeration value="CLASS"/>
 *     &lt;enumeration value="TOP_CLASS"/>
 *     &lt;enumeration value="TARGET"/>
 *     &lt;enumeration value="TOP_TARGET"/>
 *     &lt;enumeration value="ONE"/>
 *     &lt;enumeration value="PER_CHILD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "targetCoupling-type")
@XmlEnum
public enum TargetCouplingType {

    PACKAGE,
    TOP_PACKAGE,
    CLASS,
    TOP_CLASS,
    TARGET,
    TOP_TARGET,
    ONE,
    PER_CHILD;

    public String value() {
        return name();
    }

    public static TargetCouplingType fromValue(String v) {
        return valueOf(v);
    }

}
