//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 07:08:19 PM CET 
//


package sk.tuke.fei.kpi.nosal.milan.bte.metaconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wrapper-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wrapper-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="childWrapping" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="targetCoupling" type="{http://kpi.fei.tuke.sk/Nosal/Milan/BTE/metaconfiguration}targetCoupling-type"/>
 *         &lt;element name="typeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wrappedElements" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="wrapperName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wrapper-type", propOrder = {
    "childWrapping",
    "targetCoupling",
    "typeName",
    "wrappedElements",
    "wrapperName"
})
public class WrapperType {

    @XmlElement(defaultValue = "true")
    protected boolean childWrapping;
    @XmlElement(required = true, defaultValue = "PACKAGE")
    protected TargetCouplingType targetCoupling;
    @XmlElement(required = true, defaultValue = "${name}-type")
    protected String typeName;
    protected List<String> wrappedElements;
    @XmlElement(required = true)
    protected String wrapperName;

    /**
     * Gets the value of the childWrapping property.
     * 
     */
    public boolean isChildWrapping() {
        return childWrapping;
    }

    /**
     * Sets the value of the childWrapping property.
     * 
     */
    public void setChildWrapping(boolean value) {
        this.childWrapping = value;
    }

    /**
     * Gets the value of the targetCoupling property.
     * 
     * @return
     *     possible object is
     *     {@link TargetCouplingType }
     *     
     */
    public TargetCouplingType getTargetCoupling() {
        return targetCoupling;
    }

    /**
     * Sets the value of the targetCoupling property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetCouplingType }
     *     
     */
    public void setTargetCoupling(TargetCouplingType value) {
        this.targetCoupling = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the wrappedElements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wrappedElements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWrappedElements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWrappedElements() {
        if (wrappedElements == null) {
            wrappedElements = new ArrayList<String>();
        }
        return this.wrappedElements;
    }

    /**
     * Gets the value of the wrapperName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrapperName() {
        return wrapperName;
    }

    /**
     * Sets the value of the wrapperName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrapperName(String value) {
        this.wrapperName = value;
    }

}
